ResumeMVC/ResumeMVC/Controllers/ResumeController.cs
using AutoMapper;
using ResumeMVC.EDMXModel;
using ResumeMVC.Repository;
using ResumeMVC.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AutoMapper.QueryableExtensions;

namespace ResumeMVC.Controllers
{
    public class ResumeController : Controller
    {
        private readonly IResumeRepository _resumeRepository;
        public ResumeController(IResumeRepository resumeRepository)
        {
            _resumeRepository = resumeRepository;
        }

        // GET: Resume
        public ActionResult Index()
        {
            return View();
        }


        [HttpGet]
        public ActionResult PersonnalInformtion(PersonVM model)
        {
            //Nationality
            List<SelectListItem> nationality = new List<SelectListItem>()
            {
                new SelectListItem { Text = "Morocco", Value = "Morocco", Selected = true},
                new SelectListItem { Text = "India", Value = "India"},
                new SelectListItem { Text = "Spain", Value = "Spain"},
                new SelectListItem { Text = "USA", Value = "USA"},
            };


            //Educational Level
            List<SelectListItem> educationalLevel = new List<SelectListItem>()
            {
                new SelectListItem { Text = "Hight School", Value = "Hight School", Selected = true},
                new SelectListItem { Text = "Diploma", Value = "Diploma"},
                new SelectListItem { Text = "Bachelor's degree", Value = "Bachelor's degree"},
                new SelectListItem { Text = "Master's degree", Value = "Master's degree"},
                new SelectListItem { Text = "Doctorate", Value = "Doctorate"},
            };

            model.ListNationality = nationality;
            model.ListEducationalLevel = educationalLevel;

            return View(model);
        }

        [HttpPost]
        [ActionName("PersonnalInformtion")]
        public ActionResult AddPersonnalInformtion(PersonVM person)
        {

            if(ModelState.IsValid)
            {
                //Creating Mapping
                Mapper.Initialize(cfg => cfg.CreateMap<PersonVM, Person>());

                Person personEntity = Mapper.Map<Person>(person);

                HttpPostedFileBase file = Request.Files["ImageProfil"];

                bool result = _resumeRepository.AddPersonnalInformation(personEntity, file);

                if(result)
                {
                    Session["IdSelected"] = _resumeRepository.GetIdPerson(person.FirstName, person.LastName);
                    return RedirectToAction("Education");
                }
                else
                {
                    ViewBag.Message = "Something Wrong !";
                    return View(person);
                }
                
            }

            ViewBag.MessageForm = "Please Check your form before submit !";
            return View(person);

        }

        [HttpGet]
        public ActionResult Education(EducationVM education)
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddOrUpdateEducation(EducationVM education)
        {
            string msg = string.Empty;

            if(education != null)
            {
                //Creating Mapping
                Mapper.Initialize(cfg => cfg.CreateMap<EducationVM, Education>());
                Education educationEntity = Mapper.Map<Education>(education);

                int idPer = (int)Session["IdSelected"];

                msg = _resumeRepository.AddOrUpdateEducation(educationEntity, idPer);
               
            }
            else
            {
                msg = "Please re try the operation";
            }

            return Json(new { data = msg }, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public PartialViewResult EducationPartial(EducationVM education)
        {

            education.ListOfCountry = GetCountries();

            return PartialView("~/Views/Shared/_MyEducation.cshtml", education);
        }

        [HttpGet]
        public ActionResult WorkExperience()
        {
            return View();
        }

        public PartialViewResult WorkExperiencePartial(WorkExperienceVM workExperience)
        {
            workExperience.ListeOfCountries = GetCountries();

            return PartialView("~/Views/Shared/_MyWorkExperience.cshtml", workExperience);
        }

        public ActionResult AddOrUpdateExperience(WorkExperienceVM workExperience)
        {

            string msg = string.Empty;

            if (workExperience != null)
            {
                //Creating Mapping
                Mapper.Initialize(cfg => cfg.CreateMap<WorkExperienceVM, WorkExperience>());
                WorkExperience workExperienceEntity = Mapper.Map<WorkExperience>(workExperience);

                int idPer = (int)Session["IdSelected"];
               

                msg = _resumeRepository.AddOrUpdateExperience(workExperienceEntity, idPer);

            }
            else
            {
                msg = "Please re try the operation";
            }

            return Json(new { data = msg }, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult SkiCerfLang()
        {
            return View();
        }

        public PartialViewResult SkillsPartial()
        {
            return PartialView("~/Views/Shared/_MySkills.cshtml");
        }

        public ActionResult AddSkill(SkillsVM skill)
        {
            int idPer = (int)Session["IdSelected"];
            string msg = string.Empty;

            //Creating Mapping
            Mapper.Initialize(cfg => cfg.CreateMap<SkillsVM, Skill>());
            Skill skillEntity = Mapper.Map<Skill>(skill);

            if (_resumeRepository.AddSkill(skillEntity, idPer))
            {
                msg = "skill added successfully";
            }
            else
            {
                msg = "something Wrong";
            }

            return Json(new { data = msg}, JsonRequestBehavior.AllowGet);
        }

        public PartialViewResult CertificationsPartial(CertificationVM certification)
        {
            List<SelectListItem> certificationLevel = new List<SelectListItem>()
            {
                new SelectListItem { Text = "Beginner", Value = "Beginner", Selected = true},
                new SelectListItem { Text = "Intermediate", Value = "Intermediate"},
                new SelectListItem { Text = "Advanced", Value = "Advanced"}
            };

            certification.ListOfLevel = certificationLevel;

            return PartialView("~/Views/Shared/_MyCertifications.cshtml", certification);
        }

        public ActionResult AddCertification(CertificationVM certification)
        {
            int idPer = (int)Session["IdSelected"];
            string msg = string.Empty;

            //Creating Mapping
            Mapper.Initialize(cfg => cfg.CreateMap<CertificationVM, Certification>());
            Certification certificationEntity = Mapper.Map<Certification>(certification);

            if (_resumeRepository.AddCertification(certificationEntity, idPer))
            {
                msg = "Certification added successfully";
            }
            else
            {
                msg = "something Wrong";
            }

            return Json(new { data = msg }, JsonRequestBehavior.AllowGet);
        }

        public PartialViewResult LanguagePartial(LanguageVM language)
        {
            List<SelectListItem> languageLevel = new List<SelectListItem>()
            {
                new SelectListItem { Text = "Elementary Proficiency", Value = "Elementary Proficiency", Selected = true},
                new SelectListItem { Text = "LimitedWorking Proficiency", Value = "LimitedWorking Proficiency"},
                new SelectListItem { Text = "Professional working Proficiency", Value = "Professional working Proficiency"},
                new SelectListItem { Text = "Full Professional Proficiency", Value = "Full Professional Proficiency"},
                new SelectListItem { Text = "Native Or Bilingual Proficiency", Value = "Native Or Bilingual Proficiency"}
            };

            language.ListOfProficiency = languageLevel;

            return PartialView("~/Views/Shared/_MyLanguage.cshtml", language);
        }

        public ActionResult AddLanguage(LanguageVM language)
        {
            int idPer = (int)Session["IdSelected"];
            string msg = string.Empty;

            //Creating Mapping
            Mapper.Initialize(cfg => cfg.CreateMap<LanguageVM, Language>());
            Language languageEntity = Mapper.Map<Language>(language);

            if (_resumeRepository.AddLanguage(languageEntity, idPer))
            {
                msg = "Language added successfully";
            }
            else
            {
                msg = "something Wrong";
            }

            return Json(new { data = msg }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult CV()
        {
            return View();
        }

        public PartialViewResult GetPersonnalInfoPartial()
        {
            int idPer = (int)Session["IdSelected"];
            Person person = _resumeRepository.GetPersonnalInfo(idPer);

            //Creating Mapping
            Mapper.Initialize(cfg => cfg.CreateMap<Person, PersonVM>());
            PersonVM personVM = Mapper.Map<PersonVM>(person);

            return PartialView("~/Views/Shared/_MyPersonnalInfo.cshtml", personVM);
        }

        public PartialViewResult GetEducationCVPartial()
        {
            int idPer = (int)Session["IdSelected"];

            //Creating Mapping
            Mapper.Initialize(cfg => cfg.CreateMap<Education, EducationVM>());
            IQueryable<EducationVM> educationList = _resumeRepository.GetEducationById(idPer).ProjectTo<EducationVM>().AsQueryable();

ResumeMVC/ResumeMVC/Views/Resume/CV.cshtml
@{
    ViewBag.Title = "CV";
}

<style type="text/css">
    .socialMedia {
        padding-left: 16%;
    }

    .panel-default {
        width: 65%;
        margin-left: 18%;
        margin-top: 3%;
    }

    .IconTitle {
        border: 3px solid #e0e0e0;
        display: inline-block;
        width: 70px;
        height: 70px;
        border-radius: 100%;
    }

    .yearStyle {
        position: relative;
        left: 50%;
        font-size: 13px;
        color: #FFF;
        padding: 5px;
        border-radius: 4px;
        font-weight: bold;
    }

    .box {
        border: 1px solid #d0cfcf;
        padding: 16px 0px;
        border-radius: 11px;
        margin-top: 15px;
    }

    .description {
        padding: 9px 48px;
        font-size: 13px;
        color: #797575;
        font-style: italic;
    }
</style>


<div class="container">

    @{ Html.RenderAction("GetPersonnalInfoPartial", "Resume"); }

    @{ Html.RenderAction("GetEducationCVPartial", "Resume"); }

    @{ Html.RenderAction("WorkExperienceCVPartial", "Resume"); }

    @{ Html.RenderAction("SkillsCVPartial", "Resume"); }

    @{ Html.RenderAction("CertificationsCVPartial", "Resume"); }

    @{ Html.RenderAction("LanguageCVPartial", "Resume"); }

</div>

ResumeMVC/ResumeMVC/Views/Resume/Education.cshtml
@{
    ViewBag.Title = "Education";
}


@{ Html.RenderAction("EducationPartial", "Resume"); }


@section scripts {

    <script type="text/javascript">

        $(document).ready(function () {

            //Change dropdown automatically based on the selected country
            $('#Country').change(function () {

                $('#City').html('');

                $.ajax({
                    url: '@Url.Action("GetCities", "Resume")',
                    type: 'GET',
                    data: { country: $(this).val() },
                    dataType: 'Json',
                    success: function (response) {
                        console.log(response.data);

                        for(var i = 0; i < response.data.length; i++)
                        {
                            $('#City').append("<option value=" + response.data[i].Value + ">" + response.data[i].Text + "</option>");
                        }
                    },
                    error: function () {


                    }
                });
            });

            //AddOrUpdate Education

            $('#AddOrUpdateEducation').on('click', function () {

                var serializeModel = {

                    IDEdu: $('#IDEdu').val(),
                    InstituteUniversity: $('#InstituteUniversity').val(),
                    TitleOfDiploma: $('#TitleOfDiploma').val(),
                    Degree: $('#Degree').val(),
                    FromYear: $('#FromYear').val(),
                    ToYear: $('#ToYear').val(),
                    Country: $('#Country').val(),
                    City: $('#City').val()
                };
                console.log(JSON.stringify(serializeModel));

                $.ajax({

                    url: '@Url.Action("AddOrUpdateEducation", "Resume")',
                    type: 'POST',
                    data: { education: serializeModel },
                    success: function (response) {
                        alert(response.data);
                    },
                    error: function (error) {
                        alert(error.data);
                    }
                });

            });



        });

    </script>

   @Scripts.Render("~/bundles/jqueryval")

}

   

ResumeMVC/ResumeMVC/Views/Resume/Index.cshtml
@model ResumeMVC.EDMXModel.Person

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<div>

    @{ Html.RenderPartial("_View"); }


</div>


<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ResumeMVC/ResumeMVC/Views/Resume/PersonnalInformtion.cshtml
@model ResumeMVC.ViewModels.PersonVM

@{
    ViewBag.Title = "PersonnalInformtion";
}

<style type="text/css">
    .row {
        margin-bottom: 25px;
    }

    .IconTitle {
        border: 3px solid #e0e0e0;
        display: inline-block;
        width: 70px;
        height: 70px;
        border-radius: 100%;
        background-color: #269abc;
    }
</style>



<div class="container">

    <div class="PersonnelInformation FirstLevel" style="margin: 19% auto;">

        <div style="margin-left:18%;">
            <span class="IconTitle">
                <span class="glyphicon glyphicon-user" aria-hidden="true" style="margin-left:26px; margin-top: 23px; color:#FFF;"></span>
            </span>

            <h4 style="margin-left: 8%; margin-top: -4%;">Personnal Information</h4>
        </div>


        <div class="panel panel-default" style="width: 65%; margin-left: 18%; margin-top: 3%;">

            <div class="panel-heading">
                <h3 class="panel-title">Personnal Informtion</h3>
            </div> <!-- END PANEL HEADING -->

            <div class="panel-body">

            @using (Html.BeginForm("PersonnalInformtion", "Resume", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {

                    <div class="row">

                        <div class="col-xs-6">
                            <input type="file" class="form-control" name="ImageProfil" id="ImageProfil" onchange="fileCheck(this);" placeholder="Profil" style="margin: 8px 60%;" />
                        </div>

                    </div>

                    <div class="row">

                        <div class="col-xs-6">
                            @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control", @placeholder = "First Name" } })
                            @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
                        </div>

                        <div class="col-xs-6">
                            @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control", @placeholder = "Last Name" } })
                            @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
                        </div>

                    </div>

                    <div class="row">

                        <div class="col-xs-4">
                            @*@Html.EditorFor(model => model.DateOfBirth, new { htmlAttributes = new { @class = "form-control", @placeholder = "Date of Birth" } })*@
                            
                            <div class="form-group">
                                <div class="input-group date" id="datetimepicker1">
                                    @Html.EditorFor(model => model.DateOfBirth, new { htmlAttributes = new { @class = "form-control", @placeholder = "Date of Birth" } })
                                    <span class="input-group-addon">
                                        <span class="glyphicon glyphicon-calendar"></span>
                                    </span>
                                </div>
                            </div>
                            @Html.ValidationMessageFor(model => model.DateOfBirth, "", new { @class = "text-danger" })
                        </div>

                        <div class="col-xs-4">
                              @Html.DropDownListFor(model =>model.Nationality , Model.ListNationality, new { @class = "form-control" }) 
                              @Html.ValidationMessageFor(model => model.Nationality, "", new { @class = "text-danger" })
                        </div>

                        <div class="col-xs-4">
                        @Html.DropDownListFor(model => model.EducationalLevel, Model.ListEducationalLevel, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.EducationalLevel, "", new { @class = "text-danger" })
                        </div>

                    </div>

                    <div class="row">

                        <div class="col-xs-12">
                            @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control", @placeholder = "Address" } })
                            @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
                        </div>

                    </div>

                    <div class="row">

                        <div class="col-xs-6">
                            @Html.EditorFor(model => model.Tel, new { htmlAttributes = new { @class = "form-control", @placeholder = "Tel" } })
                            @Html.ValidationMessageFor(model => model.Tel, "", new { @class = "text-danger" })
                        </div>

                        <div class="col-xs-6">
                            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control", @placeholder = "E-Mail" } })
                            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                        </div>

                    </div>

                    <div class="row">

                        <div class="col-xs-3">
                            @Html.EditorFor(model => model.LinkedInProdil, new { htmlAttributes = new { @class = "form-control", @placeholder = "LinkedIn Account" } })
                            @Html.ValidationMessageFor(model => model.LinkedInProdil, "", new { @class = "text-danger" })
                        </div>

                        <div class="col-xs-3">
                            @Html.EditorFor(model => model.FaceBookProfil, new { htmlAttributes = new { @class = "form-control", @placeholder = "FaceBook Account" } })
                            @Html.ValidationMessageFor(model => model.FaceBookProfil, "", new { @class = "text-danger" })
                        </div>

                        <div class="col-xs-3">
                            @Html.EditorFor(model => model.C_CornerProfil, new { htmlAttributes = new { @class = "form-control", @placeholder = "C#Corner Account" } })
                            @Html.ValidationMessageFor(model => model.C_CornerProfil, "", new { @class = "text-danger" })
                        </div>

                        <div class="col-xs-3">
                            @Html.EditorFor(model => model.TwitterProfil, new { htmlAttributes = new { @class = "form-control", @placeholder = "Twitter Account" } })
                            @Html.ValidationMessageFor(model => model.TwitterProfil, "", new { @class = "text-danger" })
                        </div>

                    </div>

                    <div class="row">

                        <div class="col-xs-12">
                            @Html.EditorFor(model => model.Summary, new { htmlAttributes = new { @class = "form-control", @placeholder = "Summary", @rows = "8", @cols = "30" } })
                            @Html.ValidationMessageFor(model => model.Summary, "", new { @class = "text-danger" })
                        </div>
                       
                    </div>

                    <input type="submit" class="btn btn-info" style="position: relative; right: -76%;" value="Next Step>> Education"/>

                    if(ViewBag.Message != null)
                    {
                        <span> @ViewBag.Message </span>
                     }

                    if (ViewBag.MessageForm != null)
                    {
                        <span> @ViewBag.MessageForm </span>
                    }

            }

            </div> <!-- END PNEL BODY-->

        </div>

    </div>

</div> <!-- CONTAINER -->

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ResumeMVC/ResumeMVC/Views/Resume/SkiCerfLang.cshtml
@{
    ViewBag.Title = "SkiCerfLang";
}

<style type="text/css">
    .row {
        margin-bottom: 25px;
    }

    .IconTitle {
        border: 3px solid #e0e0e0;
        display: inline-block;
        width: 70px;
        height: 70px;
        border-radius: 100%;
        background-color: #2e6da4;
    }
</style>

<div class="container">

    @*Skills Partial Vue *@
    @{ Html.RenderAction("SkillsPartial", "Resume"); }


    @* Certification Partial Vue  *@

    @{ Html.RenderAction("CertificationsPartial", "Resume"); }

    @* Language Partial Vue *@

    @{ Html.RenderAction("LanguagePartial", "Resume"); }

</div>

@section Scripts {

    <script type="text/javascript">

        $(document).ready(function () {

            //Add New Skills

            $('#AddSkill').on('click', function () {

                var skill = {
                    SkillName : $('#SkillName').val()
                };

                AddNewEntity("@Url.Action("AddSkill", "Resume")", 'POST', skill);

            });

            //Add New Certification

            $('#AddCertification').on('click', function () {

                var certification = {
                    CertificationName: $('#CertificationName').val(),
                    CertificationAuthority: $('#CertificationAuthority').val(),
                    LevelCertification: $('#LevelCertification').val(),
                    FromYear: $('#FromYear').val()
                };

                AddNewEntity("@Url.Action("AddCertification", "Resume")", 'POST', certification);

            });

            //Add New Language

            $('#AddLanguage').on('click', function () {

                var language = {
                    LanguageName: $('#LanguageName').val(),
                    Proficiency: $('#Proficiency').val()
                };

                AddNewEntity("@Url.Action("AddLanguage", "Resume")", 'POST', language);

            });

            function AddNewEntity(action, type, model)
            {
                $.ajax({
                    url: action,
                    type: type,
                    data: model,
                    success: function (response) {
                        alert(response.data);
                    },
                    error: function (error) {
                        alert(error.data);
                    }
                });
            }
        });

    </script>

    @Scripts.Render("~/bundles/jqueryval")

}

ResumeMVC/ResumeMVC/Views/Resume/WorkExperience.cshtml
@{
    ViewBag.Title = "WorkExperience";
}


@{ Html.RenderAction("WorkExperiencePartial", "Resume"); }

@section Scripts {

    <script type="text/javascript">

        //AddOrUpdate Work Experience

        $('#AddOrUpdateExperience').on('click', function () {

            var serializeModel = {

                IDExp: $('#IDExp').val(),
                Company: $('#Company').val(),
                Title: $('#Title').val(),
                Country: $('#Country').val(),
                FromYear: $('#FromYear').val(),
                ToYear: $('#ToYear').val(),
                Description: $('#Description').val()
            };
            console.log(JSON.stringify(serializeModel));

            $.ajax({

                url: '@Url.Action("AddOrUpdateExperience", "Resume")',
                type: 'POST',
                data: { workExperience: serializeModel },
                success: function (response) {
                    alert(response.data);
                },
                error: function (error) {
                    alert(error.data);
                }
            });

        });

    </script>

    @Scripts.Render("~/bundles/jqueryval")

}